version: '3.8'

services:
  auth_db:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib

  auth_cache:
    image: redis:latest
    container_name: auth_cache
    ports:
      - "6379:6379"
    volumes:
      - auth_cache_data:/data

  account_db:
    image: postgres:15
    container_name: account_db
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: ${ACCOUNT_DB_USER}
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - account_db_data:/var/lib

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ADMIN_PASS}
    ports:
      - "5050:80"
    depends_on:
      - auth_db
      - account_db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  auth_db_data:
  auth_cache_data:
  account_db_data:
  rabbitmq_data: