server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  mail:
    port: 465
    protocol: smtps
    host: smtp.yandex.ru
    username: ${MAIL_USER}
    password: ${MAIL_PASS}

  datasource:
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASS}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      access-token:
        secret-key: ${JWT_ACCESS_TOKEN_SECRET_KEY}
        expiration: 3600000 # 1 hour
      refresh-token:
        secret-key: ${JWT_REFRESH_TOKEN_SECRET_KEY}
        expiration: 604800000 # 7 days
    encryption:
      secret-key: ${ENCRYPTION_SECRET_KEY}

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/