server:
  port: 8082

spring:
  application:
    name: ACCOUNT-SERVICE

  datasource:
    username: ${ACCOUNT_DB_USER}
    password: ${ACCOUNT_DB_PASS}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/account_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      access-token:
        secret-key: ${JWT_ACCESS_TOKEN_SECRET_KEY}
        expiration: 3600000 # 1 hour
      refresh-token:
        secret-key: ${JWT_REFRESH_TOKEN_SECRET_KEY}
        expiration: 604800000 # 7 days

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/